### PR TITLE
Add LUT to memory cell mapping

### PR DESCRIPTION
**Pull request by DanielHuisman**
Add mapping for Yosys LUT cells to DigitalJS memory cell.

### CODE REVIEW

**Comment by tilk** [comment]
Please don't rely on experience and check things with Yosys directly. The right place to look for the "official" behavior of various cells generated by Yosys is [simlib.v](https://github.com/YosysHQ/yosys/blob/master/techlibs/common/simlib.v#L1370). Inspecting it reveals that you are correct - the outputs are always 1-bit.

Yosys2digitaljs was not yet updated to handle recent Yosys versions. Do you know which Yosys pass emits the LUTs, and why? LUTs are very much a low-level thing, and I think it's weird that Yosys emits them without targeting an FPGA.

**Comment by DanielHuisman** [comment]
I updated the PR to be a simple LUT to memory cell mapping. This removes the need for a separate LUT cell in DigitalJS.

**Comment by DanielHuisman** [comment]
Thanks for merging this :+1: Could you also make a new npm release?

**Comment by DanielHuisman** [comment]
It has been a few months now and, as far as I can tell, there is no new release. @tilk do you have time to make a new npm release soon?

**Pull request merged**
